<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-GB9HLB2" failures="0" tests="4" name="testNG_Keywords.timeOut" time="4.045" errors="1" timestamp="2022-12-28T18:02:27 IST" skipped="0">
  <testcase classname="testNG_Keywords.timeOut" name="Testcase4" time="0.007"/>
  <system-out>
    <![CDATA[Testcase is running]]>
  </system-out>
  <testcase classname="testNG_Keywords.timeOut" name="Testcase3" time="4.018">
    <error message="Method testNG_Keywords.timeOut.Testcase3() didn&#039;t finish within the time-out 4000" type="org.testng.internal.thread.ThreadTimeoutException">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method testNG_Keywords.timeOut.Testcase3() didn't finish within the time-out 4000
at org.testng.internal.MethodInvocationHelper.invokeWithTimeoutWithNewExecutor(MethodInvocationHelper.java:384)
at org.testng.internal.MethodInvocationHelper.invokeWithTimeout(MethodInvocationHelper.java:283)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:604)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- Testcase3 -->
  <system-out>
    <![CDATA[Testcase3 is running]]>
  </system-out>
  <testcase classname="testNG_Keywords.timeOut" name="Testcase1" time="0.017"/>
  <system-out>
    <![CDATA[Testcase1 is running]]>
  </system-out>
  <testcase classname="testNG_Keywords.timeOut" name="Testcase2" time="0.003"/>
  <system-out>
    <![CDATA[Testcase2 is running]]>
  </system-out>
</testsuite> <!-- testNG_Keywords.timeOut -->
